version: '3.8'

services:
  frontend:
    build:
      context: ./app/frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build:
      context: ./app/backend
    ports:
      - "5000:5000"
